### PR TITLE
GIT-3: Use bare cloning

### PR DESCRIPTION
**Pull request by Haxsen**
Includes fixes/improvements from the previous [PR](https://github.com/xwiki-contrib/api-git/pull/5) for [GIT-3](https://jira.xwiki.org/projects/GIT/issues/GIT-3).
Let me know if this is not good.
Thanks!

### CODE REVIEW

**Comment by vmassol** [comment]
Thanks, haven't checked the content but first could you rebase and follow the instructions at https://dev.xwiki.org/xwiki/bin/view/Community/DevelopmentPractices#HRule:AlwaysputaJIRAissuereferenceincommitmessages :) thx

**Comment by Haxsen** [comment]
Sure, thanks for clearing the confusion. Updating in a few minutes :)

**Comment by Haxsen** [comment]
@vmassol Fixed the JIRA reference. Thanks for the help!

**Comment by vmassol** [comment]
@Haxsen I've merged your PR but it doesn't fix the issue :(

**Comment by vmassol** [comment]
Just build api-git and do a `git status` and you'll see by yourself...

**Comment by Haxsen** [comment]
@vmassol I couldn't see an issue. You mean: Build api-git and `git status` in the same directory or are you talking about the git repos created by the `GitScriptServiceTest` (2 repos; 1 orig, 1 cloned) ?
I `git status`'d in all 3 of them, all showed me `working tree clean`.
Can you be more specific? (I may have not understood what you mean).

**Comment by vmassol** [comment]
@Haxsen See:

```
vmassol ~/dev/xwiki/api-git (master) $ git pull --rebase
Already up to date.
Current branch master is up to date.
gvmassol ~/dev/xwiki/api-git (master) $ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
vmassol ~/dev/xwiki/api-git (master) $ mvn clean install > output.txt
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=196m; support was removed in 8.0
vmassol ~/dev/xwiki/api-git (master) $ git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	git/
	output.txt

nothing added to commit but untracked files present (use "git add" to track)
vmassol ~/dev/xwiki/api-git (master) $
```

**Comment by vmassol** [comment]
So the git/ directory should not be here.

**Comment by Haxsen** [comment]
What I understand: You built `api-git` and saved an `output.txt` (of mvn log) in the same directory, which git thinks is a new file to be added on the repository.

**Comment by vmassol** [comment]
@Haxsen please read my last message very carefully please. I'm copying it again:

> So the git/ directory should not be here.

What is hard to understand there?

Thx

**Comment by Haxsen** [comment]
Hm, I see it now.

**Comment by vmassol** [comment]
The question is: how come you built the project and did a git status and couldn't see it? That escapes me completely!

**Comment by Haxsen** [comment]
This was my error, I tested in IntelliJ and then went to /tmp/.../junit../git (where the original and cloned repository are) and made sure that my tests were not creating wrong tree.
Now I did the build and saw it myself there's a git folder in the repository (probably created by tests). I will see why it's happening now.

**Comment by Haxsen** [comment]
@vmassol the issue was with `DefaultGitManagerTest` and not `TemporaryFolder` in `GitScriptServiceTest`, where it was not specifying environment path (which the `DefaultGitManager` uses).
I've fixed the issue, sending a PR soon :)

**Pull request merged**
