### PR TITLE
a ui support

### PR DESCRIPTION
**Pull request by deeputhegamer**
please check.

### CODE REVIEW

**Comment by vmassol** [comment]
Thanks but what is this PR doing? Do you have a link to a jira issue explaining it? Thx!

**Comment by vmassol** [comment]
I think it's been pushed to the wrong git repository :)

**Comment by deeputhegamer** [comment]
Actually sir i wantes to make some changes regarding user interface that’s why i made a separate effort :)

**Comment by vmassol** [comment]
What user interface? You seem to be in the wrong project.... This is XWiki...

**Comment by deeputhegamer** [comment]
So sir what should i do to contribute 😊

**Comment by deeputhegamer** [comment]
Because this is the projects which i found interesting (in java) . I don’t have much knowledge about java but i want to increase my knowledge

**Comment by vmassol** [comment]
> So sir what should i do to contribute 😊

See https://dev.xwiki.org/xwiki/bin/view/Community/Contributing

**Pull request closed without merging**
